### ISSUE TITLE
presentation offer: writing my first haskell program! and monad transformers.

### ISSUE THREAD

**Issue by mjhoy** [HaskellMN/haskell-mn-presentations#5]
hi,

(apologies, i wanted to use google groups, however i could not figure out how to do it without a google account.)

i would like to offer talking about my VERY beginner experience writing my first actual haskell program (a bot to distribute chores fairly among my housemates every week) and in particular trying to implement the core algorithm using a monad transformer stack to handle state, randomness, configuration cleanly (or at least, more cleanly than before!) I can show the before/after monadic code, which is pretty interesting to me at least. i'd be interested in trying code up a simplified version of the algorithm live, and turn it to a monad transformer stack, although perhaps that's too complicated.

thanks.
mikey

**Comment by kmarekspartz** [comment]
That sounds great! Does March 16th work?

**Comment by mjhoy** [comment]
i think so, yes.

**Comment by kmarekspartz** [comment]
We put a description of the talk on the meetup page (and blog post / tweet / etc.) such as:

"This month, [Michael Hoy](https://github.com/mjhoy) is going to talk about his first Haskell program, a [bot](https://github.com/mjhoy/chorebot_hs) to distribute chores fairly among housemates every week. He'll discuss refactoring the bot to implement randomness and configuration through a monad transformer stack."

Does that work?

**Comment by kmarekspartz** [comment]
It would go on: http://www.meetup.com/HaskellMN/events/221323302/

**Comment by mjhoy** [comment]
looks good, thanks!

**Comment by kmarekspartz** [comment]
Added!
